server {
    listen 8080 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index de/index.html;

    location = / {
        return 302 /de/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
