// Single source of truth for release versioning.
//
// Reads a release tag (e.g. `v1.0.15`) and:
//   1. writes `lib/generated/release_info.dart` (consumed by the app),
//   2. prints machine-readable `key=value` lines to stdout (consumed by
//      Fastlane to drive `--build-name`/`--build-number`).
//
// Tag schema is plain SemVer `vMAJOR.MINOR.PATCH` — no pre-release suffix is
// accepted. Tags carrying a `-beta.N` (or any other) suffix are rejected so
// the old beta train cannot accidentally re-enter the pipeline.
//
// Build-number schema (identical on iOS and Android, deterministic from tag):
//   MAJOR * 10_000_000 + MINOR * 100_000 + PATCH * 1_000 + 999
//   The fixed `+999` suffix guarantees every new build sits strictly above the
//   legacy `vX.Y.Z-beta.N` build codes uploaded under the previous schema
//   (e.g. `v1.0.0-beta.14` → 10_000_014, so the first new build `v1.0.15` →
//   10_015_999 is comfortably higher).
//
// Limits:
//   MAJOR, MINOR, PATCH in 0..99
//   max version code   = 999_999_999 (< Play Store int32 limit 2_147_483_647)
//
// Without --tag the tool emits a `dev` sentinel so the app builds locally
// even when the generated file has never been produced.

import 'dart:io';

const _defaultOutputPath = 'lib/generated/release_info.dart';
const _stableBuildSuffix = 999;

void main(List<String> args) {
  final rawTag = _argValue(args, '--tag');
  final outputPath = _argValue(args, '--output') ?? _defaultOutputPath;
  final info = _resolve(rawTag);
  _writeReleaseInfo(info, outputPath);

  stdout.writeln('release_tag=${info.tag}');
  stdout.writeln('marketing_version=${info.marketingVersion}');
  stdout.writeln('version_code=${info.versionCode}');
}

ReleaseInfo _resolve(String? rawTag) {
  if (rawTag == null || rawTag.isEmpty || rawTag == 'dev') {
    return const ReleaseInfo(
      tag: 'dev',
      marketingVersion: '0.0.0',
      versionCode: 0,
    );
  }
  return _parseTag(rawTag);
}

ReleaseInfo _parseTag(String raw) {
  // Strip optional platform prefix used by the single-platform release
  // workflows (`android/v...`, `ios/v...`). The combined release workflows
  // use bare `vX.Y.Z` tags, so this is a no-op there.
  final unprefixed = raw.replaceFirst(RegExp(r'^(android|ios)/'), '');
  final stripped = unprefixed.startsWith('v') ? unprefixed.substring(1) : unprefixed;

  // Pre-release suffix support was removed with the v1.X.Y schema rewrite.
  // Reject anything that contains a `-`, `+` or any non-numeric/dot segment
  // so the old beta tags fail fast instead of producing surprising builds.
  if (stripped.contains('-') || stripped.contains('+')) {
    throw FormatException('Tag must be vX.Y.Z (no suffix), got: $raw');
  }

  final marketingParts = stripped.split('.');
  if (marketingParts.length != 3) {
    throw FormatException('Tag must be vX.Y.Z, got: $raw');
  }
  final major = _parseSegment(marketingParts[0], 'MAJOR', raw);
  final minor = _parseSegment(marketingParts[1], 'MINOR', raw);
  final patch = _parseSegment(marketingParts[2], 'PATCH', raw);

  final versionCode =
      major * 10000000 + minor * 100000 + patch * 1000 + _stableBuildSuffix;

  return ReleaseInfo(
    tag: stripped,
    marketingVersion: stripped,
    versionCode: versionCode,
  );
}

int _parseSegment(String segment, String name, String raw) {
  final value = int.tryParse(segment);
  if (value == null || value < 0 || value > 99) {
    throw RangeError('$name must be in 0..99 in tag: $raw');
  }
  return value;
}

String? _argValue(List<String> args, String key) {
  final prefix = '$key=';
  for (final arg in args) {
    if (arg.startsWith(prefix)) return arg.substring(prefix.length);
  }
  final flagIndex = args.indexOf(key);
  if (flagIndex >= 0 && flagIndex + 1 < args.length) {
    return args[flagIndex + 1];
  }
  return null;
}

void _writeReleaseInfo(ReleaseInfo info, String outputPath) {
  final file = File(outputPath);
  final dir = file.parent;
  if (!dir.existsSync()) dir.createSync(recursive: true);

  final content =
      '// GENERATED by tool/generate_release_info.dart — do not edit.\n\n'
      "const String releaseTag = '${info.tag}';\n"
      "const String releaseMarketingVersion = '${info.marketingVersion}';\n"
      'const int releaseVersionCode = ${info.versionCode};\n';

  file.writeAsStringSync(content);
}

class ReleaseInfo {
  const ReleaseInfo({
    required this.tag,
    required this.marketingVersion,
    required this.versionCode,
  });

  final String tag;
  final String marketingVersion;
  final int versionCode;
}
