// Single source of truth for release versioning.
//
// Reads a release tag (e.g. `v1.0.0-beta.2`) and:
//   1. writes `lib/generated/release_info.dart` (consumed by the app),
//   2. prints machine-readable `key=value` lines to stdout (consumed by
//      Fastlane to drive `--build-name`/`--build-number`).
//
// Build-number schema (identical on iOS and Android, deterministic from tag):
//   MAJOR * 10_000_000 + MINOR * 100_000 + PATCH * 1_000 + BETA_N
//   stable releases use BETA_N = 999, so every stable is strictly higher
//   than any beta inside the same X.Y.Z train.
//
// Limits:
//   MAJOR, MINOR, PATCH in 0..99
//   BETA_N             in 1..998
//   max version code   = 999_999_999 (< Play Store int32 limit 2_147_483_647)
//
// Without --tag the tool emits a `dev` sentinel so the app builds locally
// even when the generated file has never been produced.

import 'dart:io';

const _defaultOutputPath = 'lib/generated/release_info.dart';
const _stableBetaN = 999;
const _maxBetaN = 998;

void main(List<String> args) {
  final rawTag = _argValue(args, '--tag');
  final outputPath = _argValue(args, '--output') ?? _defaultOutputPath;
  final info = _resolve(rawTag);
  _writeReleaseInfo(info, outputPath);

  stdout.writeln('release_tag=${info.tag}');
  stdout.writeln('marketing_version=${info.marketingVersion}');
  stdout.writeln('version_code=${info.versionCode}');
  stdout.writeln('is_stable=${info.isStable}');
}

ReleaseInfo _resolve(String? rawTag) {
  if (rawTag == null || rawTag.isEmpty || rawTag == 'dev') {
    return const ReleaseInfo(
      tag: 'dev',
      marketingVersion: '0.0.0',
      versionCode: 0,
      isStable: false,
    );
  }
  return _parseTag(rawTag);
}

ReleaseInfo _parseTag(String raw) {
  // Strip optional platform prefix used by the single-platform release
  // workflows (`android/v...`, `ios/v...`). The combined develop-release
  // workflow uses bare `vX.Y.Z[-beta.N]` tags, so this is a no-op there.
  final unprefixed = raw.replaceFirst(RegExp(r'^(android|ios)/'), '');
  final stripped = unprefixed.startsWith('v') ? unprefixed.substring(1) : unprefixed;
  final parts = stripped.split('-');

  final marketing = parts.first;
  final marketingParts = marketing.split('.');
  if (marketingParts.length != 3) {
    throw FormatException('Tag must be vX.Y.Z[-beta.N], got: $raw');
  }
  final major = _parseSegment(marketingParts[0], 'MAJOR', raw);
  final minor = _parseSegment(marketingParts[1], 'MINOR', raw);
  final patch = _parseSegment(marketingParts[2], 'PATCH', raw);

  int betaN;
  bool isStable;
  if (parts.length == 1) {
    betaN = _stableBetaN;
    isStable = true;
  } else if (parts.length == 2 && parts[1].startsWith('beta.')) {
    final n = int.tryParse(parts[1].substring('beta.'.length));
    if (n == null || n < 1 || n > _maxBetaN) {
      throw RangeError('beta number must be in 1..$_maxBetaN, got: $raw');
    }
    betaN = n;
    isStable = false;
  } else {
    throw FormatException('Tag must be vX.Y.Z[-beta.N], got: $raw');
  }

  final versionCode =
      major * 10000000 + minor * 100000 + patch * 1000 + betaN;

  return ReleaseInfo(
    tag: stripped,
    marketingVersion: marketing,
    versionCode: versionCode,
    isStable: isStable,
  );
}

int _parseSegment(String segment, String name, String raw) {
  final value = int.tryParse(segment);
  if (value == null || value < 0 || value > 99) {
    throw RangeError('$name must be in 0..99 in tag: $raw');
  }
  return value;
}

String? _argValue(List<String> args, String key) {
  final prefix = '$key=';
  for (final arg in args) {
    if (arg.startsWith(prefix)) return arg.substring(prefix.length);
  }
  final flagIndex = args.indexOf(key);
  if (flagIndex >= 0 && flagIndex + 1 < args.length) {
    return args[flagIndex + 1];
  }
  return null;
}

void _writeReleaseInfo(ReleaseInfo info, String outputPath) {
  final file = File(outputPath);
  final dir = file.parent;
  if (!dir.existsSync()) dir.createSync(recursive: true);

  final content =
      '// GENERATED by tool/generate_release_info.dart — do not edit.\n\n'
      "const String releaseTag = '${info.tag}';\n"
      "const String releaseMarketingVersion = '${info.marketingVersion}';\n"
      'const int releaseVersionCode = ${info.versionCode};\n'
      'const bool releaseIsStable = ${info.isStable};\n';

  file.writeAsStringSync(content);
}

class ReleaseInfo {
  const ReleaseInfo({
    required this.tag,
    required this.marketingVersion,
    required this.versionCode,
    required this.isStable,
  });

  final String tag;
  final String marketingVersion;
  final int versionCode;
  final bool isStable;
}
