# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def get_api_key
  app_store_connect_api_key(
    key_id: ENV['FASTLANE_APPLE_API_KEY_ID'],
    issuer_id: ENV['FASTLANE_APPLE_API_ISSUER_ID'],
    key_filepath: ENV['FASTLANE_APPLE_API_KEY_PATH'],
  )
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    match(
      type: "appstore",
      app_identifier: "swiss.dfx.realunit",
      api_key: get_api_key,
      git_url: "git@github.com:DFXswiss/fastlane-certificates.git"
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      # export_xcargs: '-allowProvisioningUpdates',
      export_options: {
        signingStyle: "manual"
      }
    )

    upload_to_testflight(
      api_key: get_api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
