# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def get_api_key
  app_store_connect_api_key(
    key_id: ENV['FASTLANE_APPLE_API_KEY_ID'],
    issuer_id: ENV['FASTLANE_APPLE_API_ISSUER_ID'],
    key_filepath: ENV['FASTLANE_APPLE_API_KEY_PATH'],
  )
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci

    raw_version_name = ENV["NEW_VERSION"] || "v0.0.0"
    new_version_name = raw_version_name.delete('v')
    latest_build = latest_testflight_build_number(api_key: get_api_key)

    sync_code_signing(
      type: "appstore",
      app_identifier: "swiss.realunit.app",
      api_key: get_api_key,
      git_url: "git@github.com:DFXswiss/fastlane-certificates.git"
    )

    increment_version_number(
      version_number: new_version_name,
      xcodeproj: "Runner.xcodeproj"
    )
    
    increment_build_number(
      build_number: latest_build + 1,  
      xcodeproj: "Runner.xcodeproj"
    )
    
    gym(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      output_name: "realunit-#{new_version_name}.ipa",
      xcargs: "-verbose",
      verbose: true
    )

    upload_to_testflight(
      api_key: get_api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
