#!/usr/bin/env bash
#
# Assemble the 268 handbook screenshots from the visual-regression Golden
# baselines. The flat `NN-name.png` output layout matches what
# docs/handbook/de/index.html links to (`<img src="../screenshots/NN-name.png">`
# — the relative path resolves to `docs/handbook/screenshots/NN-name.png`).
#
# Usage:
#   scripts/assemble-handbook-screenshots.sh <output-dir>
#
# Used by:
#   - Dockerfile.handbook (multi-stage build → /usr/share/nginx/html/screenshots/)
#   - local previews (`scripts/assemble-handbook-screenshots.sh docs/handbook/screenshots`
#     before opening docs/handbook/de/index.html; the target dir is git-ignored)
#
# Source of truth for every handbook page is one Golden PNG under
# `test/goldens/<area>/goldens/macos/<file>.png`, where <area> is `screens/`
# (nearly all) or `widgets/` (shared widgets such as the phone-number field).
# The mapping table below was established in the gap-audit on PR #568 and later
# extended to cover every Golden baseline. When a new
# handbook page is added, append a row here AND add the corresponding
# Golden test — never source a screenshot from anywhere else.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <output-dir>" >&2
  exit 2
fi

OUT="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GOLDENS_ROOT="$REPO_ROOT/test/goldens"

mkdir -p "$OUT"

# handbook-name → golden path relative to test/goldens/ (under screens/ or widgets/)
# Not every entry has a maestro flow: only slots 01–26 have a companion
# .maestro/handbook/*.yaml smoke flow; slots 27+ are golden-only.
MAPPING=(
  "01-welcome=screens/home/goldens/macos/home_page_default.png"
  "02-create-vs-restore=screens/welcome/goldens/macos/welcome_page_ios.png"
  "03-software-wallet-terms=screens/welcome/goldens/macos/welcome_page_second_step.png"
  "04-seed-hidden=screens/create_wallet/goldens/macos/create_wallet_page_default.png"
  "05-seed-revealed=screens/create_wallet/goldens/macos/create_wallet_page_revealed.png"
  "06-verify-seed=screens/verify_seed/goldens/macos/verify_seed_page_default.png"
  "07-onboarding-completed=screens/onboarding/goldens/macos/onboarding_completed_page_default.png"
  "08-pin-setup=screens/pin/goldens/macos/setup_pin_page_default.png"
  "09-pin-confirm=screens/pin/goldens/macos/setup_pin_page_confirming.png"
  "10-biometric-prompt=screens/pin/goldens/macos/biometric_prompt_sheet_default.png"
  "11-dashboard=screens/home/goldens/macos/home_page_loaded.png"
  "12-settings=screens/settings/goldens/macos/settings_page_default.png"
  "13-settings-languages=screens/settings_languages/goldens/macos/settings_languages_page_default.png"
  "14-settings-currency=screens/settings_currencies/goldens/macos/settings_currencies_page_default.png"
  "15-settings-network=screens/settings_network/goldens/macos/settings_network_page_default.png"
  "16-settings-wallet-address=screens/settings_wallet_address/goldens/macos/settings_wallet_address_page_default.png"
  "17-settings-backup-pin=screens/pin/goldens/macos/verify_pin_page_seed_backup.png"
  "18-settings-seed-hidden=screens/settings_seed/goldens/macos/settings_seed_page_default.png"
  "19-settings-seed-revealed=screens/settings_seed/goldens/macos/settings_seed_page_revealed.png"
  "20-settings-legal-documents=screens/settings_legal_documents/goldens/macos/settings_legal_documents_page_default.png"
  "21-settings-aktionariat-documents=screens/settings_legal_documents/goldens/macos/settings_aktionariat_documents_page_default.png"
  "22-settings-dfx-documents=screens/settings_legal_documents/goldens/macos/settings_dfx_documents_page_default.png"
  "23-settings-contact=screens/settings_contact/goldens/macos/settings_contact_page_default.png"
  "24-settings-delete-wallet=screens/settings/goldens/macos/settings_confirm_logout_wallet_sheet_default.png"
  "25-restore-wallet=screens/restore_wallet/goldens/macos/restore_wallet_page_default.png"
  "26-terms=screens/legal/goldens/macos/legal_document_page_terms_loaded.png"
  "27-software-wallet-disclaimer-step-0=screens/legal/goldens/macos/legal_disclaimer_step_0.png"
  "28-software-wallet-disclaimer-step-1=screens/legal/goldens/macos/legal_disclaimer_step_1.png"
  "29-legal-documents-step=screens/legal/goldens/macos/legal_documents_step_default.png"
  "30-legal-aktionariat-step=screens/legal/goldens/macos/legal_aktionariat_step_default.png"
  "31-legal-dfx-step=screens/legal/goldens/macos/legal_dfx_step_default.png"
  "32-restore-wallet-valid=screens/restore_wallet/goldens/macos/restore_wallet_page_valid.png"
  "33-restore-wallet-invalid=screens/restore_wallet/goldens/macos/restore_wallet_page_invalid.png"
  "34-verify-seed-completed=screens/verify_seed/goldens/macos/verify_seed_page_all_entered.png"
  "35-dashboard-with-balance=screens/dashboard/goldens/macos/dashboard_with_balance.png"
  "36-transaction-history=screens/transaction_history/goldens/macos/transaction_history_page_with_transactions.png"
  "37-kyc-email-loading=screens/kyc/goldens/macos/kyc_email_page_loading.png"
  "38-kyc-email-mismatch=screens/kyc/goldens/macos/kyc_email_page_does_not_match.png"
  "39-kyc-email-error=screens/kyc/goldens/macos/kyc_email_page_unknown_error.png"
  "40-kyc-registration-personal=screens/kyc/goldens/macos/kyc_registration_personal_step_default.png"
  "41-kyc-registration-address=screens/kyc/goldens/macos/kyc_registration_address_step_default.png"
  "42-settings-tax-report-loading=screens/settings_tax_report/goldens/macos/settings_tax_report_page_loading.png"
  "43-settings-tax-report-failure=screens/settings_tax_report/goldens/macos/settings_tax_report_page_failure.png"
  "44-buy-loading=screens/buy/goldens/macos/buy_payment_info_loading.png"
  "45-buy-registration-required=screens/buy/goldens/macos/buy_registration_required.png"
  "46-buy-kyc-required=screens/buy/goldens/macos/buy_kyc_required.png"
  "47-buy-min-amount=screens/buy/goldens/macos/buy_min_amount_not_met.png"
  "48-buy-unknown-error=screens/buy/goldens/macos/buy_unknown_error.png"
  "49-sell-loading=screens/sell/goldens/macos/sell_payment_info_loading.png"
  "50-sell-kyc-required=screens/sell/goldens/macos/sell_kyc_required.png"
  "51-sell-min-amount=screens/sell/goldens/macos/sell_min_amount_not_met.png"
  "52-sell-unknown-error=screens/sell/goldens/macos/sell_unknown_error.png"
  "53-buy-payment-details=screens/buy/goldens/macos/buy_payment_details_default.png"
  "54-kyc-registration-personal-dropdown=screens/kyc/goldens/macos/kyc_registration_personal_step_dropdown_open.png"
  "55-kyc-registration-address-dropdown=screens/kyc/goldens/macos/kyc_registration_address_step_dropdown_open.png"
  "56-kyc-registration-tax=screens/kyc/goldens/macos/kyc_registration_tax_step_default.png"
  "57-kyc-registration-tax-dropdown=screens/kyc/goldens/macos/kyc_registration_tax_step_dropdown_open.png"
  "58-kyc-registration-tax-swiss=screens/kyc/goldens/macos/kyc_registration_tax_step_swiss.png"
  "59-kyc-registration-tax-non-swiss=screens/kyc/goldens/macos/kyc_registration_tax_step_non_swiss.png"
  "60-kyc-registration-tax-country-error=screens/kyc/goldens/macos/kyc_registration_tax_step_country_error.png"
  "61-kyc-registration-tax-tin-error=screens/kyc/goldens/macos/kyc_registration_tax_step_tin_error.png"
  "62-welcome-page-android=screens/welcome/goldens/macos/welcome_page_android.png"
  "63-create-wallet-page-loading=screens/create_wallet/goldens/macos/create_wallet_page_loading.png"
  "64-verify-seed-page-verifying=screens/verify_seed/goldens/macos/verify_seed_page_verifying.png"
  "65-verify-seed-page-verified=screens/verify_seed/goldens/macos/verify_seed_page_verified.png"
  "66-verify-seed-page-error=screens/verify_seed/goldens/macos/verify_seed_page_error.png"
  "67-verify-seed-page-commit-failed=screens/verify_seed/goldens/macos/verify_seed_page_commit_failed.png"
  "68-verify-seed-page-empty=screens/verify_seed/goldens/macos/verify_seed_page_empty.png"
  "69-restore-wallet-page-complete=screens/restore_wallet/goldens/macos/restore_wallet_page_complete.png"
  "70-restore-wallet-page-restoring=screens/restore_wallet/goldens/macos/restore_wallet_page_restoring.png"
  "71-restore-wallet-page-success=screens/restore_wallet/goldens/macos/restore_wallet_page_success.png"
  "72-restore-wallet-page-failed=screens/restore_wallet/goldens/macos/restore_wallet_page_failed.png"
  "73-setup-pin-page-submitting=screens/pin/goldens/macos/setup_pin_page_submitting.png"
  "74-setup-pin-page-confirm-mismatch=screens/pin/goldens/macos/setup_pin_page_confirm_mismatch.png"
  "75-setup-pin-page-store-failed=screens/pin/goldens/macos/setup_pin_page_store_failed.png"
  "76-verify-pin-page-default=screens/pin/goldens/macos/verify_pin_page_default.png"
  "77-verify-pin-page-verifying=screens/pin/goldens/macos/verify_pin_page_verifying.png"
  "78-verify-pin-page-biometric-button=screens/pin/goldens/macos/verify_pin_page_biometric_button.png"
  "79-verify-pin-page-biometric-hint=screens/pin/goldens/macos/verify_pin_page_biometric_hint.png"
  "80-verify-pin-page-biometric-hint-not-enrolled=screens/pin/goldens/macos/verify_pin_page_biometric_hint_not_enrolled.png"
  "81-verify-pin-page-biometric-hint-unavailable=screens/pin/goldens/macos/verify_pin_page_biometric_hint_unavailable.png"
  "82-verify-pin-page-failure=screens/pin/goldens/macos/verify_pin_page_failure.png"
  "83-verify-pin-page-temporarily-locked=screens/pin/goldens/macos/verify_pin_page_temporarily_locked.png"
  "84-verify-pin-page-locked=screens/pin/goldens/macos/verify_pin_page_locked.png"
  "85-verify-pin-page-unverifiable=screens/pin/goldens/macos/verify_pin_page_unverifiable.png"
  "86-verify-pin-page-app-lock=screens/pin/goldens/macos/verify_pin_page_app_lock.png"
  "87-verify-pin-page-unverifiable-app-lock=screens/pin/goldens/macos/verify_pin_page_unverifiable_app_lock.png"
  "88-forgot-pin-bottom-sheet-default=screens/pin/goldens/macos/forgot_pin_bottom_sheet_default.png"
  "89-dashboard-empty=screens/dashboard/goldens/macos/dashboard_empty.png"
  "90-dashboard-price-chart=screens/dashboard/goldens/macos/dashboard_price_chart.png"
  "91-dashboard-portfolio-chart=screens/dashboard/goldens/macos/dashboard_portfolio_chart.png"
  "92-dashboard-pending-transactions=screens/dashboard/goldens/macos/dashboard_pending_transactions.png"
  "93-dashboard-recent-transactions=screens/dashboard/goldens/macos/dashboard_recent_transactions.png"
  "94-dashboard-hidden-amounts=screens/dashboard/goldens/macos/dashboard_hidden_amounts.png"
  "95-transaction-history-page-default=screens/transaction_history/goldens/macos/transaction_history_page_default.png"
  "96-transaction-history-page-list=screens/transaction_history/goldens/macos/transaction_history_page_list.png"
  "97-transaction-history-page-date-picker=screens/transaction_history/goldens/macos/transaction_history_page_date_picker.png"
  "98-transaction-history-row-receipt-loading=screens/transaction_history/goldens/macos/transaction_history_row_receipt_loading.png"
  "99-transaction-history-row-receipt-failure=screens/transaction_history/goldens/macos/transaction_history_row_receipt_failure.png"
  "100-transaction-history-multi-receipt-loading=screens/transaction_history/goldens/macos/transaction_history_multi_receipt_loading.png"
  "101-receive-page-default=screens/receive/goldens/macos/receive_page_default.png"
  "102-receive-page-full-page=screens/receive/goldens/macos/receive_page_full_page.png"
  "103-buy-initial=screens/buy/goldens/macos/buy_initial.png"
  "104-buy-payment-info-loaded=screens/buy/goldens/macos/buy_payment_info_loaded.png"
  "105-buy-currency-picker-open=screens/buy/goldens/macos/buy_currency_picker_open.png"
  "106-buy-currency-load-failed=screens/buy/goldens/macos/buy_currency_load_failed.png"
  "107-buy-primary-email-required=screens/buy/goldens/macos/buy_primary_email_required.png"
  "108-buy-bitbox-disconnected=screens/buy/goldens/macos/buy_bitbox_disconnected.png"
  "109-buy-price-source-unavailable=screens/buy/goldens/macos/buy_price_source_unavailable.png"
  "110-buy-confirm-loading=screens/buy/goldens/macos/buy_confirm_loading.png"
  "111-buy-confirm-failed-aktionariat=screens/buy/goldens/macos/buy_confirm_failed_aktionariat.png"
  "112-buy-confirm-failed-amount-too-low=screens/buy/goldens/macos/buy_confirm_failed_amount_too_low.png"
  "113-buy-confirm-failed-unknown=screens/buy/goldens/macos/buy_confirm_failed_unknown.png"
  "114-buy-payment-details-qr-details-tab=screens/buy/goldens/macos/buy_payment_details_qr_details_tab.png"
  "115-buy-payment-details-qr-code-tab=screens/buy/goldens/macos/buy_payment_details_qr_code_tab.png"
  "116-buy-payment-details-qr-code-tab-svg=screens/buy/goldens/macos/buy_payment_details_qr_code_tab_svg.png"
  "117-buy-payment-details-no-purpose=screens/buy/goldens/macos/buy_payment_details_no_purpose.png"
  "118-sell-no-account-zero-balance=screens/sell/goldens/macos/sell_no_account_zero_balance.png"
  "119-sell-with-balance=screens/sell/goldens/macos/sell_with_balance.png"
  "120-sell-bank-account-selected=screens/sell/goldens/macos/sell_bank_account_selected.png"
  "121-sell-bank-account-selection-page-default=screens/sell/goldens/macos/sell_bank_account_selection_page_default.png"
  "122-sell-add-bank-account-sheet=screens/sell/goldens/macos/sell_add_bank_account_sheet.png"
  "123-sell-confirm-sheet=screens/sell/goldens/macos/sell_confirm_sheet.png"
  "124-sell-confirm-sheet-loading=screens/sell/goldens/macos/sell_confirm_sheet_loading.png"
  "125-sell-executed-sheet=screens/sell/goldens/macos/sell_executed_sheet.png"
  "126-sell-bitbox-page-default=screens/sell_bitbox/goldens/macos/sell_bitbox_page_default.png"
  "127-sell-bitbox-waiting-for-eth=screens/sell_bitbox/goldens/macos/sell_bitbox_waiting_for_eth.png"
  "128-sell-bitbox-eth-ready=screens/sell_bitbox/goldens/macos/sell_bitbox_eth_ready.png"
  "129-sell-bitbox-preparing-swap=screens/sell_bitbox/goldens/macos/sell_bitbox_preparing_swap.png"
  "130-sell-bitbox-awaiting-swap-confirm=screens/sell_bitbox/goldens/macos/sell_bitbox_awaiting_swap_confirm.png"
  "131-sell-bitbox-swapping=screens/sell_bitbox/goldens/macos/sell_bitbox_swapping.png"
  "132-sell-bitbox-awaiting-deposit-confirm=screens/sell_bitbox/goldens/macos/sell_bitbox_awaiting_deposit_confirm.png"
  "133-sell-bitbox-depositing=screens/sell_bitbox/goldens/macos/sell_bitbox_depositing.png"
  "134-sell-bitbox-retrying-deposit=screens/sell_bitbox/goldens/macos/sell_bitbox_retrying_deposit.png"
  "135-sell-bitbox-deposit-retry=screens/sell_bitbox/goldens/macos/sell_bitbox_deposit_retry.png"
  "136-sell-bitbox-confirm-retry=screens/sell_bitbox/goldens/macos/sell_bitbox_confirm_retry.png"
  "137-connect-bitbox-page-default=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_default.png"
  "138-connect-bitbox-page-default-ios=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_default_ios.png"
  "139-connect-bitbox-page-connecting=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_connecting.png"
  "140-connect-bitbox-page-check-hash=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_check_hash.png"
  "141-connect-bitbox-page-pairing=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_pairing.png"
  "142-connect-bitbox-page-capturing-signature=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_capturing_signature.png"
  "143-connect-bitbox-page-connected=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_connected.png"
  "144-connect-bitbox-page-not-initialized=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_not_initialized.png"
  "145-connect-bitbox-page-signature-failed=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_signature_failed.png"
  "146-connect-bitbox-page-failed-snackbar=screens/hardware_connect_bitbox/goldens/macos/connect_bitbox_page_failed_snackbar.png"
  "147-bitbox-address-recovery-page-default=screens/hardware_connect_bitbox/goldens/macos/bitbox_address_recovery_page_default.png"
  "148-kyc-email-page-default=screens/kyc/goldens/macos/kyc_email_page_default.png"
  "149-kyc-email-page-error-snackbar-does-not-match=screens/kyc/goldens/macos/kyc_email_page_error_snackbar_does_not_match.png"
  "150-kyc-email-page-error-snackbar-unknown=screens/kyc/goldens/macos/kyc_email_page_error_snackbar_unknown.png"
  "151-kyc-confirm-email-page-default=screens/kyc/goldens/macos/kyc_confirm_email_page_default.png"
  "152-kyc-email-verification-page-default=screens/kyc/goldens/macos/kyc_email_verification_page_default.png"
  "153-kyc-email-verification-page-loading=screens/kyc/goldens/macos/kyc_email_verification_page_loading.png"
  "154-kyc-email-verification-page-loading-bitbox=screens/kyc/goldens/macos/kyc_email_verification_page_loading_bitbox.png"
  "155-kyc-email-verification-page-error-snackbar=screens/kyc/goldens/macos/kyc_email_verification_page_error_snackbar.png"
  "156-kyc-2fa-page-default=screens/kyc/goldens/macos/kyc_2fa_page_default.png"
  "157-kyc-2fa-page-verify-loading=screens/kyc/goldens/macos/kyc_2fa_page_verify_loading.png"
  "158-kyc-2fa-page-resend-loading=screens/kyc/goldens/macos/kyc_2fa_page_resend_loading.png"
  "159-kyc-2fa-page-verify-failure=screens/kyc/goldens/macos/kyc_2fa_page_verify_failure.png"
  "160-kyc-2fa-page-request-code-failure=screens/kyc/goldens/macos/kyc_2fa_page_request_code_failure.png"
  "161-kyc-registration-page-default=screens/kyc/goldens/macos/kyc_registration_page_default.png"
  "162-kyc-registration-page-prefilled=screens/kyc/goldens/macos/kyc_registration_page_prefilled.png"
  "163-kyc-registration-personal-step-account-type-open=screens/kyc/goldens/macos/kyc_registration_personal_step_account_type_open.png"
  "164-kyc-registration-personal-step-phone-prefix-open=screens/kyc/goldens/macos/kyc_registration_personal_step_phone_prefix_open.png"
  "165-kyc-registration-personal-step-validation-error=screens/kyc/goldens/macos/kyc_registration_personal_step_validation_error.png"
  "166-kyc-registration-page-address-step=screens/kyc/goldens/macos/kyc_registration_page_address_step.png"
  "167-kyc-registration-address-step-validation-error=screens/kyc/goldens/macos/kyc_registration_address_step_validation_error.png"
  "168-kyc-registration-page-tax-step=screens/kyc/goldens/macos/kyc_registration_page_tax_step.png"
  "169-kyc-registration-page-submit-loading=screens/kyc/goldens/macos/kyc_registration_page_submit_loading.png"
  "170-kyc-registration-page-submit-failure-snackbar=screens/kyc/goldens/macos/kyc_registration_page_submit_failure_snackbar.png"
  "171-kyc-registration-page-forwarding-failed-snackbar=screens/kyc/goldens/macos/kyc_registration_page_forwarding_failed_snackbar.png"
  "172-kyc-registration-page-bitbox-required=screens/kyc/goldens/macos/kyc_registration_page_bitbox_required.png"
  "173-kyc-nationality-page-default=screens/kyc/goldens/macos/kyc_nationality_page_default.png"
  "174-kyc-nationality-page-dropdown-open=screens/kyc/goldens/macos/kyc_nationality_page_dropdown_open.png"
  "175-kyc-nationality-page-country-loading=screens/kyc/goldens/macos/kyc_nationality_page_country_loading.png"
  "176-kyc-nationality-page-country-error=screens/kyc/goldens/macos/kyc_nationality_page_country_error.png"
  "177-kyc-nationality-page-submit-loading=screens/kyc/goldens/macos/kyc_nationality_page_submit_loading.png"
  "178-kyc-nationality-page-submit-failure=screens/kyc/goldens/macos/kyc_nationality_page_submit_failure.png"
  "179-kyc-nationality-page-validation-error=screens/kyc/goldens/macos/kyc_nationality_page_validation_error.png"
  "180-kyc-financial-data-page-default=screens/kyc/goldens/macos/kyc_financial_data_page_default.png"
  "181-kyc-financial-data-loading-page-default=screens/kyc/goldens/macos/kyc_financial_data_loading_page_default.png"
  "182-kyc-financial-data-page-fallback=screens/kyc/goldens/macos/kyc_financial_data_page_fallback.png"
  "183-kyc-financial-data-failure-page-default=screens/kyc/goldens/macos/kyc_financial_data_failure_page_default.png"
  "184-kyc-financial-data-page-submit-failure=screens/kyc/goldens/macos/kyc_financial_data_page_submit_failure.png"
  "185-kyc-financial-data-questions-page-default=screens/kyc/goldens/macos/kyc_financial_data_questions_page_default.png"
  "186-kyc-financial-data-questions-page-no-description=screens/kyc/goldens/macos/kyc_financial_data_questions_page_no_description.png"
  "187-kyc-financial-data-questions-page-answered=screens/kyc/goldens/macos/kyc_financial_data_questions_page_answered.png"
  "188-kyc-financial-data-questions-page-single-choice=screens/kyc/goldens/macos/kyc_financial_data_questions_page_single_choice.png"
  "189-kyc-financial-data-questions-page-multiple-choice=screens/kyc/goldens/macos/kyc_financial_data_questions_page_multiple_choice.png"
  "190-kyc-financial-data-questions-page-checkbox=screens/kyc/goldens/macos/kyc_financial_data_questions_page_checkbox.png"
  "191-kyc-financial-data-questions-page-link-description=screens/kyc/goldens/macos/kyc_financial_data_questions_page_link_description.png"
  "192-kyc-financial-data-questions-page-not-last=screens/kyc/goldens/macos/kyc_financial_data_questions_page_not_last.png"
  "193-kyc-ident-page-default=screens/kyc/goldens/macos/kyc_ident_page_default.png"
  "194-kyc-ident-page-loading=screens/kyc/goldens/macos/kyc_ident_page_loading.png"
  "195-kyc-ident-page-error=screens/kyc/goldens/macos/kyc_ident_page_error.png"
  "196-kyc-ident-page-finally-rejected=screens/kyc/goldens/macos/kyc_ident_page_finally_rejected.png"
  "197-kyc-link-wallet-page-default=screens/kyc/goldens/macos/kyc_link_wallet_page_default.png"
  "198-kyc-link-wallet-page-bitbox-required=screens/kyc/goldens/macos/kyc_link_wallet_page_bitbox_required.png"
  "199-kyc-link-wallet-page-submitting=screens/kyc/goldens/macos/kyc_link_wallet_page_submitting.png"
  "200-kyc-link-wallet-page-success=screens/kyc/goldens/macos/kyc_link_wallet_page_success.png"
  "201-kyc-link-wallet-page-failure=screens/kyc/goldens/macos/kyc_link_wallet_page_failure.png"
  "202-kyc-link-wallet-page-missing-user-data=screens/kyc/goldens/macos/kyc_link_wallet_page_missing_user_data.png"
  "203-kyc-signature-unsupported-page-default=screens/kyc/goldens/macos/kyc_signature_unsupported_page_default.png"
  "204-kyc-loading-page-default=screens/kyc/goldens/macos/kyc_loading_page_default.png"
  "205-kyc-pending-page-default=screens/kyc/goldens/macos/kyc_pending_page_default.png"
  "206-kyc-completed-page-default=screens/kyc/goldens/macos/kyc_completed_page_default.png"
  "207-kyc-failure-page-default=screens/kyc/goldens/macos/kyc_failure_page_default.png"
  "208-kyc-manual-review-page-default=screens/kyc/goldens/macos/kyc_manual_review_page_default.png"
  "209-kyc-account-merge-page-default=screens/kyc/goldens/macos/kyc_account_merge_page_default.png"
  "210-kyc-merge-processing-page-default=screens/kyc/goldens/macos/kyc_merge_processing_page_default.png"
  "211-settings-page-bitbox=screens/settings/goldens/macos/settings_page_bitbox.png"
  "212-settings-confirm-logout-wallet-sheet-checked=screens/settings/goldens/macos/settings_confirm_logout_wallet_sheet_checked.png"
  "213-settings-languages-page-loading=screens/settings_languages/goldens/macos/settings_languages_page_loading.png"
  "214-settings-languages-page-error=screens/settings_languages/goldens/macos/settings_languages_page_error.png"
  "215-settings-currencies-page-loading=screens/settings_currencies/goldens/macos/settings_currencies_page_loading.png"
  "216-settings-currencies-page-error=screens/settings_currencies/goldens/macos/settings_currencies_page_error.png"
  "217-settings-network-page-switching=screens/settings_network/goldens/macos/settings_network_page_switching.png"
  "218-settings-seed-page-loading=screens/settings_seed/goldens/macos/settings_seed_page_loading.png"
  "219-settings-security-page-default=screens/settings_security/goldens/macos/settings_security_page_default.png"
  "220-settings-security-page-biometrics-disabled=screens/settings_security/goldens/macos/settings_security_page_biometrics_disabled.png"
  "221-settings-security-page-no-biometrics=screens/settings_security/goldens/macos/settings_security_page_no_biometrics.png"
  "222-settings-security-page-busy=screens/settings_security/goldens/macos/settings_security_page_busy.png"
  "223-settings-security-page-error-snackbar=screens/settings_security/goldens/macos/settings_security_page_error_snackbar.png"
  "224-settings-tax-report-page-default=screens/settings_tax_report/goldens/macos/settings_tax_report_page_default.png"
  "225-settings-tax-report-page-date-picker=screens/settings_tax_report/goldens/macos/settings_tax_report_page_date_picker.png"
  "226-settings-tax-report-page-failure-snackbar=screens/settings_tax_report/goldens/macos/settings_tax_report_page_failure_snackbar.png"
  "227-settings-user-data-page-default=screens/settings_user_data/goldens/macos/settings_user_data_page_default.png"
  "228-settings-user-data-page-editable=screens/settings_user_data/goldens/macos/settings_user_data_page_editable.png"
  "229-settings-user-data-page-pending=screens/settings_user_data/goldens/macos/settings_user_data_page_pending.png"
  "230-settings-user-data-page-no-birthday=screens/settings_user_data/goldens/macos/settings_user_data_page_no_birthday.png"
  "231-settings-user-data-page-email-only=screens/settings_user_data/goldens/macos/settings_user_data_page_email_only.png"
  "232-settings-user-data-page-empty=screens/settings_user_data/goldens/macos/settings_user_data_page_empty.png"
  "233-settings-user-data-page-loading=screens/settings_user_data/goldens/macos/settings_user_data_page_loading.png"
  "234-settings-user-data-page-failure=screens/settings_user_data/goldens/macos/settings_user_data_page_failure.png"
  "235-settings-user-data-page-bitbox-disconnected=screens/settings_user_data/goldens/macos/settings_user_data_page_bitbox_disconnected.png"
  "236-settings-edit-name-page-default=screens/settings_user_data/goldens/macos/settings_edit_name_page_default.png"
  "237-settings-edit-phone-number-page-default=screens/settings_user_data/goldens/macos/settings_edit_phone_number_page_default.png"
  "238-settings-edit-address-page-default=screens/settings_user_data/goldens/macos/settings_edit_address_page_default.png"
  "239-settings-edit-loading-page-default=screens/settings_user_data/goldens/macos/settings_edit_loading_page_default.png"
  "240-settings-edit-pending-page-default=screens/settings_user_data/goldens/macos/settings_edit_pending_page_default.png"
  "241-settings-edit-failure-page-default=screens/settings_user_data/goldens/macos/settings_edit_failure_page_default.png"
  "242-legal-disclaimer-page-default=screens/legal/goldens/macos/legal_disclaimer_page_default.png"
  "243-legal-document-page-default=screens/legal/goldens/macos/legal_document_page_default.png"
  "244-legal-document-page-loaded-with-pdf=screens/legal/goldens/macos/legal_document_page_loaded_with_pdf.png"
  "245-legal-document-page-load-error=screens/legal/goldens/macos/legal_document_page_load_error.png"
  "246-support-page-default=screens/support/goldens/macos/support_page_default.png"
  "247-support-email-capture-page-default=screens/support/goldens/macos/support_email_capture_page_default.png"
  "248-support-email-capture-page-submitting=screens/support/goldens/macos/support_email_capture_page_submitting.png"
  "249-support-email-capture-page-buy-flow=screens/support/goldens/macos/support_email_capture_page_buy_flow.png"
  "250-support-create-ticket-page-default=screens/support/goldens/macos/support_create_ticket_page_default.png"
  "251-support-create-ticket-page-filled=screens/support/goldens/macos/support_create_ticket_page_filled.png"
  "252-support-create-ticket-page-submitting=screens/support/goldens/macos/support_create_ticket_page_submitting.png"
  "253-support-tickets-page-default=screens/support/goldens/macos/support_tickets_page_default.png"
  "254-support-tickets-page-loading=screens/support/goldens/macos/support_tickets_page_loading.png"
  "255-support-tickets-page-loaded=screens/support/goldens/macos/support_tickets_page_loaded.png"
  "256-support-tickets-page-error=screens/support/goldens/macos/support_tickets_page_error.png"
  "257-support-chat-page-default=screens/support/goldens/macos/support_chat_page_default.png"
  "258-support-chat-page-loaded=screens/support/goldens/macos/support_chat_page_loaded.png"
  "259-support-chat-page-sending=screens/support/goldens/macos/support_chat_page_sending.png"
  "260-support-chat-page-closed=screens/support/goldens/macos/support_chat_page_closed.png"
  "261-support-chat-page-error=screens/support/goldens/macos/support_chat_page_error.png"
  "262-debug-auth-page-default=screens/debug_auth/goldens/macos/debug_auth_page_default.png"
  "263-debug-auth-page-fetching=screens/debug_auth/goldens/macos/debug_auth_page_fetching.png"
  "264-debug-auth-page-error=screens/debug_auth/goldens/macos/debug_auth_page_error.png"
  "265-debug-auth-page-sign-message=screens/debug_auth/goldens/macos/debug_auth_page_sign_message.png"
  "266-debug-auth-page-clipboard-snackbar=screens/debug_auth/goldens/macos/debug_auth_page_clipboard_snackbar.png"
  "267-debug-auth-page-authenticating=screens/debug_auth/goldens/macos/debug_auth_page_authenticating.png"
  "268-phone-number-field-default=widgets/form/goldens/macos/phone_number_field_default.png"
)

missing=()
for entry in "${MAPPING[@]}"; do
  name="${entry%%=*}"
  src_rel="${entry#*=}"
  src="$GOLDENS_ROOT/$src_rel"
  if [ ! -f "$src" ]; then
    missing+=("$name → $src_rel")
    continue
  fi
  cp "$src" "$OUT/$name.png"
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "error: handbook-screenshot sources missing from Goldens:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  echo >&2
  echo "Run the visual-regression suite + commit baselines, or update the" >&2
  echo "mapping in $0 to point at an existing Golden." >&2
  exit 1
fi

count=$(ls -1 "$OUT"/*.png | wc -l | tr -d ' ')
echo "assembled $count handbook screenshots into $OUT"
