name: Create GitHub Release Android

on:
  push:
    branches:
      - "feat/fastlane-android"
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Android Beta"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: "stable"
          cache: true

      - name: Build release APK
        run: |
          flutter build apk \
            --release \
            --no-tree-shake-icons \
            --obfuscate \
            --split-debug-info=build/debug_info

      - name: Create GitHub Release and attach APK
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.apk
          generate_release_notes: true
