name: Build & Upload iOS Beta

on:
  workflow_dispatch:
  push:
    branches:
      - feat/fastlane

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      

      # Install gems using Bundler
      - name: Install fastlane & dependencies
        run: |
          cd ios
          bundle install --jobs 4 --retry 3
        working-directory: ios

      - name: Get flutter packages
        run: flutter pub get

      # Install CocoaPods via Bundler
      - name: Install CocoaPods
        run: bundle exec pod install --repo-update
        working-directory: ios
  
      - name: Build & Upload
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APP_SPECIFIC_PASSWORD }}
        run: bundle exec fastlane ios beta
        working-directory: ios