name: Build & Upload iOS Beta

on:
  workflow_dispatch:
  push:
    branches:
      - feat/fastlane

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH for Fastlane Match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # ------------------------------------
      # 1. Setup Environment
      # ------------------------------------
      
      - name: 🐦 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: 📦 Install Flutter Dependencies
        run: flutter pub get

      - name: 💊 Install iOS Pods
        run: |
          cd ios
          pod install --repo-update

      # ------------------------------------
      # 2. Setup Fastlane
      # ------------------------------------
      
      - name: 💎 Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: false
      
      - name: Install Bundler
        run: gem install bundler -v 2.7.2
      
      - name: Install Gems
        run: bundle _2.7.2_ install
        working-directory: ios

      # ------------------------------------
      # 3. Build & Deploy
      # ------------------------------------

      - name: 🚀 Run Fastlane Deployment Lane
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_KEY }}" > ./AuthKey.p8
          bundle exec fastlane beta
        working-directory: ios
        env:
          FASTLANE_APPLE_API_KEY_PATH: ./AuthKey.p8
          FASTLANE_APPLE_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          FASTLANE_APPLE_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: ✅ Deployment Complete
        run: echo "Successfully triggered Fastlane lane beta"

